version: '3'
services:
  react:
    build: .
    volumes:
     - ./react:/usr/src/app
    command: sh -c "cd vending-machine && yarn start"
    ports:
     - "13000:3000"

# 初回起動時
# docker-compose build
# docker-compose run --rm react sh -c "npx create-react-app vending-machine"
# docker-compose run --rm react sh -c "yarn add axios"
# docker-compose up -d